name: go_action

on:
  push:
    branches: [ "master" ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:
  go_job:
    uses: charvey77/node-latest-centos/.github/workflows/release-build.yml@v0_4
